cloudify-cosmo/cloudify-aws-plugin

ec2/securitygroup.py
ec2/tests/test_ec2_securitygroup.py
plugin.yaml
system_tests/local/test_plugin.py

* Adding the authorize another security group feature
* updating the existing tests to not break when we add this feature

Add new authorize feature

---

ec2/connection.py
ec2/constants.py
ec2/tests/blueprint/blueprint.yaml
ec2/tests/test_ec2_connect.py
ec2/tests/test_ec2_elasticip.py
ec2/tests/test_ec2_instance.py
ec2/tests/test_ec2_keypair.py
ec2/tests/test_ec2_securitygroup.py
ec2/tests/test_ec2_utils.py
ec2/utils.py
plugin.yaml
system_tests/local/ec2_test_utils.py
system_tests/resources/relationships.yaml
system_tests/resources/simple.yaml

All of these files were changed while trying to build an implementation ......of the aws_configure field.

add aws_configure to plugin

---

ec2/configure.py
ec2/tests/test_ec2_configure.py

Updated configure.py to use the ConfigParser and StringIO libraries

Updated to use ConfigParser

---

system_tests/manager/aws_ec2_nodecellar_tests.py

Push this when https://github.com/cloudify-cosmo/cloudify-nodecellar-example/pull/61 is approved

switching the name of the nodecellar endpoint node template id

---

ec2/constants.py
ec2/ebs.py
ec2/instance.py
ec2/tests/test_ec2_ebs.py
ec2/tests/test_ec2_instance.py
plugin.yaml
system_tests/ec2_handler.py
system_tests/local/ec2_test_utils.py
system_tests/local/test_plugin.py
system_tests/manager/aws_ec2_user_data_agent_install_test.py
system_tests/manager/resources/relationships-blueprint.yaml
system_tests/manager/resources/simple-blueprint.yaml

EBS is AWS Virtual Block Storage volume service
- Adding AWS Volume Type to plugin.yaml
- Adding EBS module to EC2 Package
- EBS constants to contsants.py
- Added unit testssss
- add system tests

Adding EBS

---

ec2/instance.py
ec2/tests/test_ec2_instance.py
plugin.yaml

added the _add_tags private function to instance
added the name property to cloudify.node.aws.Instance
added one test
added an assert to an existing test

Adding Name Tagging to Instance

---

plugin.yaml
vpc/routetable.py
vpc/tests/blueprint/blueprint.yaml
vpc/tests/blueprint/plugin.yaml

added the destination_cidr_block input to the route_table_to_gateway
relationship operation
and added test

Added destination_cidr_block input

---

system_tests/ec2_handler.py

added a check for security group vpc and subnet to check if they are default and to avoid if they are

added checks for default

---

system_tests/ec2_handler.py

the bug is that the clean up removes resources out of order of their dependencies

fixing bug in cleanup

---

system_tests/ec2_handler.py
system_tests/local/test_vpc.py
system_tests/local/vpc_test_utils.py
system_tests/manager/resources/vpc_test_blueprint.yaml
vpc/vpc.py

vpn_gateway customer_gateway vpcs all have various dependencies
this handles them'

hanldes dependency situations

---

vpc/vpc.py

does not always add the return route to the correct route table

fix minor bug in vpc peering

---

system_tests/ec2_handler.py

that we want to delete is in the list of instances

checks if the instance id

---

ec2/constants.py
ec2/elasticip.py
ec2/instance.py
ec2/tests/test_ec2_elasticip.py
ec2/tests/test_ec2_instance.py
ec2/utils.py
plugin.yaml

Check provider context for agents vpc before create

CFY-5163 Create Elastic IP in Manager VPC 

---

cloudify_aws/ec2/instance.py

Results in "EC2 instance instance"

Fixed logging message

---

CHANGELOG.txt
cloudify_aws/eks/__init__.py
cloudify_aws/eks/resources/cluster.py
cloudify_aws/eks/resources/node_group.py
cloudify_aws/eks/tests/test_cluster.py
cloudify_aws/eks/tests/test_nodegroup.py
examples/eks-feature-demo/blueprint.yaml
examples/eks-feature-demo/scripts/store_kube_token.py
plugin.yaml
setup.py

In order to support [ create node_group -needed to create nodes in the EKS cluster- ] , we had to upgrade boto since the old one that we were using only support create EKS cluster only , without the node-group
old : https://boto3.amazonaws.com/v1/documentation/api/1.9.75/reference/services/eks.html
vs
new : https://boto3.amazonaws.com/v1/documentation/api/1.12.13/reference/services/eks.html

CY-2266-Support-EKS-With-Boto3-Upgrade

---

cloudify_aws/ec2/resources/routetable.py
cloudify_aws/ec2/tests/test_routetable.py

Changed the implementation of attach/detach to support many subnets associations

CY-2446-Support-Multi-Subnet-RouteTable-Association

---

examples/eks-feature-demo/blueprint.yaml
examples/eks-feature-demo/scripts/store_kube_token.py

CY-2266-Update-Example

---

CHANGELOG.txt
cloudify_aws/ec2/__init__.py
cloudify_aws/ec2/resources/ebs.py
cloudify_aws/ec2/resources/subnet.py
cloudify_aws/ec2/tests/test_ebs.py
cloudify_aws/ec2/tests/test_subnet.py
plugin.yaml
setup.py

added a simple check before creating the resource that takes Availability zone as input

CY-2801-Availability-Zone-Retry

---

.circleci/package_release.py

fix release

---

.circleci/merge_docs.py
.circleci/package_release.py

merge docs

---

CHANGELOG.txt
plugin.yaml

fix build system bug

---

CHANGELOG.txt
cloudify_aws/common/tests/test_utils.py
cloudify_aws/common/utils.py
plugin.yaml

handle nonstring tags

---

cloudify_aws/codepipeline/resources/pipeline.py
cloudify_aws/codepipeline/tests/test_pipeline.py
plugin.yaml

added start_pipeline_execution operation

---

.circleci/config.yml
CHANGELOG.txt
cloudify_aws/ec2/resources/routetable.py
plugin.yaml

RD-815: Added relationship for main route table

---

cloudify_aws/lambda_serverless/resources/function.py
cloudify_aws/lambda_serverless/resources/invoke.py
cloudify_aws/lambda_serverless/tests/test_function.py
plugin.yaml

Payload payload bytes are read, but this cannot be dumped into runtime property.
This code adds parsing of the response payload (and additionally data inside which also is json)

Fix payload in request and reponse for Lambda call

---

CHANGELOG.txt
cloudify_aws/common/decorators.py
cloudify_aws/ec2/resources/instances.py
examples/elb-feature-demo/blueprint.yaml
plugin.yaml

add default tagging methods to decorators.py

add cloudify_tag property to plugin.yaml
